<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body></body>
  <script>
    //-------------------------------pyramid of doom----------------------------
    // Q.if you have promises like p1 - p5 and you want to  resolve p2 when p1 is resolved similarly
    //  p3 when p2 is resolved.like  in a chain  format  if anyone is reject return error ?(pyramid of doom)

    //Ans- we can solve it by using .then or await but the problem with .then is like it will
    //create messy code and if we have a large data it become impossible to debugging in them
    //using .then. this is known as callback hell  .

    // But  using await it become easy to do that it help us to write the clean code.and save time.

    const P1 = async () => {
      return new Promise((resolve, reject) => {
        resolve(1);
      });
    };

    const P2 = async () => {
      return new Promise((resolve, reject) => {
        reject(2);
      });
    };

    const P3 = async () => {
      return new Promise((resolve, reject) => {
        reject(3);
      });
    };
    const P4 = async () => {
      return new Promise((resolve, reject) => {
        reject(4);
      });
    };

    const P5 = async () => {
      return new Promise((resolve, reject) => {
        resolve(5);
      });
    };

    //-----------------------------Using.then-----------------------------
    P1()
      .then((data) => {
        console.log(data);

        P2()
          .then((data) => {
            console.log(data);
            P3()
              .then((data) => {
                console.log(data);

                P4()
                  .then((data) => {
                    console.log(data);

                    P5()
                      .then((data) => {
                        console.log(data);
                      })
                      .catch((err) => {
                        console.log(err);
                      });
                  })
                  .catch((err) => {
                    console.log(err);
                  });
              })
              .catch((err) => {
                console.log(err);
              });
          })
          .catch((err) => {
            console.log(err);
          });
      })
      .catch((err) => {
        console.log(err);
      });

    // -----------------------------------Using async await-----------------------------

    const runPromises = async () => {
      const p1Response = await P1().catch((err) => null);
      console.log(p1Response);
      if (!p1Response) {
        console.log("P1 failed");
        return "P1 failed";
      }

      const p2Response = await P2().catch((err) => null); // condition hui true kynki resolve h
      // console.log("!", !p2Response);
      console.log(p2Response);
      if (!p2Response) {
        //not operator se condotion hue false. if ki statment chalegi jb condition true hogi.

        console.log("P2 failed");
        return;
      }

      const p3Response = await P3().catch((err) => null);
      console.log("!", !p3Response);
      console.log(p3Response); // null
      if (!p3Response) {
        console.log("P3 failed"); // err msg
        return; // stop execution when reject
      }

      const p4Response = await P4().catch((err) => null);
      console.log(p4Response);
      if (!p4Response) {
        console.log("P4 failed");
        return "P4 failed";
      }

      const p5Response = await P5().catch((err) => null);
      console.log(p5Response);
      if (!p5Response) {
        console.log("P5 failed");
        return "P5 failed";
      }

      // return "Done";
    };
    runPromises();
  </script>
</html>
